name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Sử dụng PAT_TOKEN thay cho GITHUB_TOKEN

      # Show the status of the build
      - name: Show build status
        run: git status

      # Checkout the "output" branch to push the new snake images there
      - name: Checkout output branch
        run: |
          git fetch origin
          git checkout -B output origin/output || git checkout --orphan output

      # Copy the generated files to output branch
      - name: Copy generated files to output branch
        run: |
          cp -r dist/* .

      # Push the new files to the output branch
      - name: Push new snake images to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .
          commit_message: "Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Sử dụng PAT_TOKEN thay cho GITHUB_TOKEN

      # Clean up the directory after pushing
      - name: Clean up
        run: git reset --hard
